var malemarwari = ["Aatma", "Abhay", "Abhijeet", "Abhimanyu", "Abhishek", "Adarsh", "Aditya", "Ajay", "Ajit", "Akshay", "Ambika", "Arjun", "Arvind", "Badri", "Bajrang", "Baldev", "Balwant", "Beni Ram", "Bhagwat", "Bhanuprasad", "Bharat", "Bhogilal", "Chandi", "Chitranjan", "Daulat Ram", "Devendra", "Devi Dutt", "Devilaal", "Dungar", "Gajendra", "Ghanshyam", "Gokul", "Gopal Das", "Gopal", "Goplilal", "Gyan", "Hanuman", "Hanumanbax", "Hanumant", "Hanut", "Har Lal", "Hari", "Hariram", "Jagat", "Jagdish", "Jamna", "Jaskaur", "Jaswant", "Jawahar", "Jhabar", "Jorawar", "Kailash", "Kalyan", "Kamalesh", "Kanhaiya", "Kanhaiya Lal", "Karni", "Keshwanand", "Kesri", "Khailashankar", "Kripal", "Krishna", "Kudrat", "Lakshmi", "Limba", "Madhukar", "Mag Raj", "Magan", "Man Mohan", "Manik", "Mohan", "Mohanlal", "Moti", "Muni", "Nagendra", "Namo", "Nand Kishore", "Narayan", "Naresh", "Nathuram", "Natwar", "Nawal", "Nrisingh", "Parthasarathy", "Prabhu", "Purshottam", "Radheyshyam", "Raghubir", "Raj", "Rajendra", "Rajesh", "Rajyashree", "Rajyavardhan", "Ram Gopal", "Ram Niwas", "Ratan", "Roop", "Sagarmal", "Sagat", "Satish", "Saurabh", "Sees Ram", "Sheetal", "Shridhar", "Shyam", "Sita Ram", "Sriram", "Subhash", "Sunil", "Suraj", "Surya", "Tejraj", "Udai", "Veer", "Vijay", "Vijaydan", "Vikram", "Vikrant", "Virendar", "Vishwa", "Vivek"];

var femalemarwari = ["Aarti", "Aastha", "Abhilasha", "Aishwarya", "Akanksha", "Alka", "Amanpreet", "Amba", "Ambika", "Amisha", "Anita", "Anju", "Anuradha", "Aparna", "Archana", "Asha", "Babita", "Barkha", "Basanti", "Bela", "Bhagwati", "Bhagyashri", "Bhairavi", "Bhanu", "Bhanumati", "Bhanupriya", "Bharti", "Bhavana", "Bhavani", "Bhuvaneshwari", "Bijli", "Biju", "Bimla", "Bindiya", "Bindu", "Chakori", "Chameli", "Champa", "Chanchal", "Chanda", "Chandni", "Chetna", "Chhaya", "Damini", "Deepa", "Deepali", "Deepika", "Deepti", "Dharmini", "Divya", "Durga", "Durgesh", "Durgeshwari", "Eila", "Ganga", "Gangotri", "Garima", "Geeta", "Geetanjali", "Girja", "Gowri", "Heena", "Hema", "Hemlata", "Himani", "Indira", "Indrani", "Jaishree", "Jamuna", "Janki", "Jaya", "Jayalaksmi", "Jayanti", "Jyoti", "Kajal", "Kalpana", "Kamala", "Kamini", "Kamlesh", "Kanti", "Karishma", "Karuna", "Kavita", "Khushi", "Komal", "Krishna", "Kushboo", "Kusum", "Lakshmi", "Lalita", "Lata", "Leelawati", "Madhavi", "Madhu", "Madhuri", "Maheswari", "Mahima", "Mala", "Malti", "Mamta", "Mandakini", "Mangala", "Manju", "Manorama", "Mansi", "Maya", "Meena", "Meenakshi", "Meenu", "Meera", "Megha", "Mehandi", "Menka", "Mohini", "Mridula", "Mukta", "Naina", "Nanda", "Nandini", "Neelam", "Neena", "Neera", "Neetu", "Nidhi", "Nirmala", "Padma", "Parvati", "Payal", "Pooja", "Poonam", "Poornima", "Prachi", "Pratibha", "Pratiksha", "Prema", "Prerana", "Priya", "Priyanka", "Pushpa", "Rachana", "Radha", "Radhika", "Ragini", "Rakhi", "Richa", "Ritu", "Rohini", "Roopa", "Rushi", "Sadhana", "Sandhya", "Sangeeta", "Sapna", "Saraswati", "Shruti", "Sweta; Shweta", "Tanushree", "Usha", "Varsha", "Vimla"];

var unionSuffixMarwari = [...malemarwari, ...femalemarwari];

module.exports = {
  malemarwari,
  femalemarwari,
  unionSuffixMarwari
};
